version: '3.2'
services:
  db:
    image: postgres:latest
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "database:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: controller
      POSTGRES_USER: picam
      POSTGRES_HOST_AUTH_METHOD: trust
  controller:
    image: tommymaintz/mlmocap-controller:latest
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "recordings:/home/pi/recordings"
    ports:
      - "3000:3000"
    environment:
      DEBUG: "false"
      PORT: 3000
      DATABASE_URL: postgresql://picam@db/controller
      LOCAL_STORAGE_PATH: /home/pi/recordings/local
      REMOTE_STORAGE_PATH: /home/pi/recordings/remote
volumes:
  recordings:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.1.1.1,nolock,soft,rw"
      device: ":/home/pi/nfs/recordings"
  database:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.1.1.1,nolock,soft,rw"
      device: ":/home/pi/nfs/db"

