version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: controller
      POSTGRES_USER: picam
      POSTGRES_PASSWORD: ######
  controller:
    build: controller
    command: watchmedo auto-restart -p="*.py" -R pipenv run python ./app.py
    volumes:
      - ./controller:/usr/src/app
      - /home/pi/recordings:/home/pi/recordings
    restart: always
    ports:
    - "3000:3000"
    environment:
      DEBUG: "false"
      PORT: 3000
      DATABASE_URL: postgresql://picam:######@db/controller
      LOCAL_STORAGE_PATH: /home/pi/recordings/local
      REMOTE_STORAGE_PATH: /home/pi/recordings/remote
    links:
    - db
  ui:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/usr/src/app
    restart: always
    ports:
    - "4200:4200"
    links:
    - controller    
