---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: mlmocap-camera
  namespace: mlmocap
spec:
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
    spec:
      nodeSelector:
        node-role.kubernetes.io/camera: camera
      containers:
        - name: camera
          image: tommymaintz/mlmocap-camera:latest
          securityContext:
            privileged: true
          volumeMounts:
          - name: nfs-recordings
            mountPath: "/home/pi/recordings"
          - name: node-pipe
            mountPath: /dev/hostpipe
          env:
          - name: CAMERA_ID
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CONTROLLER_HOST
            value: api
      volumes:
      - name: nfs-recordings
        persistentVolumeClaim:
          claimName: recordings
      - name: node-pipe
        hostPath:
          path: /dev/hostpipe
          type: File
