---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: mlmocap-camera
  namespace: mlmocap
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: camera
  template:
    metadata:
      labels:
        app: camera
    spec:
      nodeSelector:
        node-role.kubernetes.io/camera: camera
      containers:
        - name: camera
          image: tommymaintz/mlmocap-camera:latest
          volumeMounts:
          - name: nfs-recordings
            mountPath: "/home/pi/recordings"
      volumes:
      - name: nfs-recordings
        persistentVolumeClaim:
          claimName: recordings
