---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mlmocap-database
  namespace: mlmocap
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      nodeSelector:
        node-role.kubernetes.io/controller: controller
      containers:
        - name: database
          image: postgres:latest
          ports:
          - containerPort: 5432
            name: postgres
          securityContext:
            privileged: true
          volumeMounts:
          - name: nfs-database
            mountPath: "/var/lib/postgresql/data"
          env:
          - name: POSTGRES_DB
            value: controller
          - name: POSTGRES_USER
            value: mlmocap
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
      volumes:
      - name: nfs-database
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: mlmocap
  labels:
    app: database
spec:
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
  selector:
    app: database
